### ISSUE TITLE
webpack-dev-server 运行报错

### ISSUE THREAD

**Issue by shuxiongwuziqi** [roscoe054/webpack-examples#129]
pack.json
{
  "name": "learning_webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "raw-loader": "^4.0.2",
    "webpack": "^5.37.0",
    "webpack-cli": "^4.7.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "dev": "webpack-dev-server"
  },
  "author": "",
  "license": "ISC"
}
命令行输入 npm run dev报错：
> learning_webpack@1.0.0 dev C:\Users\13065\Desktop\我自己做一遍\learning_webpack
> webpack-dev-server

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\13065\Desktop\我自己做一遍\learning_webpack\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\13065\Desktop\我自己做一遍\learning_webpack\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\13065\\Desktop\\我自己做一遍\\learning_webpack\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! learning_webpack@1.0.0 dev: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learning_webpack@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\13065\AppData\Roaming\npm-cache\_logs\2021-05-19T03_16_57_335Z-debug.log

**请问这个问题如何解决呢？**

**Comment by newliangzai** [comment]
解决：

1.卸载当前的 webpack-cli npm uninstall webpack-cli

2.安装 webpack-cli 3.* 版本 npm install webpack-cli@3 -D
